Call ``resolve()`` with correct arguments for pip 20.2.
